// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrKrR9NqlybhVEtg0Rdc0oCGWaiQJpxQs',
    appId: '1:61865980374:android:48d397491c4e492acc7477',
    messagingSenderId: '61865980374',
    projectId: 'auto-vr',
    databaseURL: 'https://auto-vr.firebaseio.com',
    storageBucket: 'auto-vr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM3PWA2bxx8h7ex_AHbfzZcf3YhxiTwhc',
    appId: '1:61865980374:ios:1ef0323ba15fa483cc7477',
    messagingSenderId: '61865980374',
    projectId: 'auto-vr',
    databaseURL: 'https://auto-vr.firebaseio.com',
    storageBucket: 'auto-vr.appspot.com',
    iosClientId: '61865980374-4o6qto5p3l9f5b7dd7crfl620g6pdcr5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
